import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { NotesProvider } from "@/context/NotesContext";
import { DailyTodos } from "@/components/DailyTodos";
vi.mock("@/lib/firebase", () => ({ auth: null, db: null }));
afterEach(() => { cleanup(); localStorage.clear(); });
it("writes checkbox lines, inserts with Enter, strikes through in place, and persists per day", async () => {
  const view = render(<NotesProvider><DailyTodos /></NotesProvider>);
  fireEvent.change(screen.getByRole("textbox", { name: "New todo" }), { target: { value: "Buy milk" } });
  const first = screen.getByRole("textbox", { name: "Todo line 1" }) as HTMLTextAreaElement;
  await waitFor(() => expect(document.activeElement).toBe(first));
  first.setSelectionRange(first.value.length, first.value.length);
  fireEvent.keyDown(first, { key: "Enter" });
  const second = screen.getByRole("textbox", { name: "Todo line 2" });
  await waitFor(() => expect(document.activeElement).toBe(second));
  fireEvent.change(second, { target: { value: "Read book" } });
  fireEvent.click(screen.getByRole("checkbox", { name: "Complete Buy milk" }));
  expect(first.className).toContain("line-through");
  expect(first.value).toBe("Buy milk");
  fireEvent.click(screen.getByRole("button", { name: "Next day" }));
  expect(screen.queryByRole("checkbox")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Previous day" }));
  expect(screen.getByRole("checkbox", { name: "Complete Buy milk" }).getAttribute("aria-checked")).toBe("true");
  view.unmount();
  render(<NotesProvider><DailyTodos /></NotesProvider>);
  expect((screen.getByRole("textbox", { name: "Todo line 2" }) as HTMLTextAreaElement).value).toBe("Read book");
  const line = screen.getByRole("textbox", { name: "Todo line 2" });
  fireEvent.change(line, { target: { value: "" } });
  fireEvent.keyDown(line, { key: "Backspace" });
  expect(screen.queryByRole("textbox", { name: "Todo line 2" })).toBeNull();
  expect(JSON.parse(localStorage.getItem("mynotes-data")!)).toHaveLength(1);
});
it("splits a line at the cursor and ignores Enter during composition", async () => {
  render(<NotesProvider><DailyTodos /></NotesProvider>);
  fireEvent.change(screen.getByRole("textbox", { name: "New todo" }), { target: { value: "FirstSecond" } });
  const first = screen.getByRole("textbox", { name: "Todo line 1" }) as HTMLTextAreaElement;
  await waitFor(() => expect(document.activeElement).toBe(first));
  fireEvent.keyDown(first, { key: "Enter", isComposing: true });
  expect(screen.queryByRole("textbox", { name: "Todo line 2" })).toBeNull();
  first.setSelectionRange(5, 5);
  fireEvent.keyDown(first, { key: "Enter" });
  await waitFor(() => expect((screen.getByRole("textbox", { name: "Todo line 2" }) as HTMLTextAreaElement).value).toBe("Second"));
  expect(first.value).toBe("First");
});
it("turns pasted lines into separate checkboxes", async () => {
  render(<NotesProvider><DailyTodos /></NotesProvider>);
  fireEvent.change(screen.getByRole("textbox", { name: "New todo" }), { target: { value: "One\nTwo\nThree" } });
  await waitFor(() => expect(screen.getAllByRole("checkbox")).toHaveLength(3));
  expect((screen.getByRole("textbox", { name: "Todo line 2" }) as HTMLTextAreaElement).value).toBe("Two");
  fireEvent.click(screen.getByRole("checkbox", { name: "Complete Two" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Complete Two" }));
  expect(screen.getByRole("textbox", { name: "Todo line 2" }).className).not.toContain("line-through");
});
