import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { NotesProvider } from "@/context/NotesContext";
import { DailyTodos } from "@/components/DailyTodos";
vi.mock("@/lib/firebase", () => ({ auth: null, db: null }));
afterEach(() => { cleanup(); localStorage.clear(); });
it("adds, edits, completes, filters and persists tasks separately for each day", () => {
  const view = render(<NotesProvider><DailyTodos /></NotesProvider>);
  const input = screen.getByRole("textbox", { name: "New todo" });
  fireEvent.change(input, { target: { value: "  Buy milk  " } });
  fireEvent.click(screen.getByRole("button", { name: "Add" }));
  fireEvent.click(screen.getByRole("button", { name: "Buy milk" }));
  fireEvent.change(screen.getByRole("textbox", { name: "Edit task" }), { target: { value: "Buy oat milk" } });
  fireEvent.keyDown(screen.getByRole("textbox", { name: "Edit task" }), { key: "Enter" });
  fireEvent.click(screen.getByRole("checkbox", { name: "Complete Buy oat milk" }));
  expect(screen.getByText("1 of 1 done")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Active" }));
  expect(screen.queryByRole("checkbox")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: /^All$/ }));
  fireEvent.click(screen.getByRole("button", { name: "Next day" }));
  expect(screen.queryByRole("checkbox")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Previous day" }));
  expect(screen.getByRole("checkbox").getAttribute("aria-checked")).toBe("true");
  view.unmount();
  render(<NotesProvider><DailyTodos /></NotesProvider>);
  expect(screen.getByRole("checkbox").getAttribute("aria-checked")).toBe("true");
  fireEvent.click(screen.getByRole("button", { name: "Delete Buy oat milk" }));
  expect(within(screen.getByRole("list")).queryByRole("listitem")).toBeNull();
  expect(JSON.parse(localStorage.getItem("mynotes-data")!)).toEqual([]);
});
